### ISSUE TITLE
LaTeX2e 2020-10-01 検討状況

### ISSUE THREAD

**Issue by aminophen** [texjporg/tests-shipout#1]
皆様のご協力により aminophen/platex-tools#15, aminophen/platex-tools#16, aminophen/plautopatch#12 のコメント内に挙がっているテストケースは大方取り込めたと思います。ご協力ありがとうございます。

対策の実装検討にあたっては：

* スタートは「[\AtBeginDvi の再定義 (ref. texjporg/platex#94) を削除した pLaTeX](https://github.com/texjporg/platex/tree/atbegindvi)」を基準とします。
* 実装案はトップディレクトリに置く platex.cfg というファイルに書き込めば十分です。（※「platex / platex-dev 起動直後にファイル platex.cfg が読み込まれる」という仕様を積極的に活用。）
* この実装が問題ないかどうかは，トップディレクトリで `make` した時にエラーなく実行され，生成する *-test.pdf にも問題ないことをもって確認とします。
* 理想としては「新しい pLaTeX を使えば plautopatch (pxeveryshi, pxatbegshi, ...) 無しでも正常に `make` できる」という状態が良いのですが，難しければ問いません。

既に出ていた案については

* 候補1 (01.../platex-01.cfg)
    * 方針：フックをそのまま活用して `\AddToHook{shipout/before}{\yoko}` を実行
    * 問題：フックの順序入替がある場合，onlyfloat.tex で `! Use \yoko at top of list.`
* 候補2 (01.../platex-02.cfg)
    * 方針：フック直前行にプレースホルダを設置，pLaTeX の OR でプレースホルダに \yoko を投入
    * 問題：やはり onlyfloat.tex で `! Use \yoko at top of list.`

と，今のところ安全な方法を見出せていません。

https://github.com/aminophen/platex-tools/pull/16#issuecomment-691794512 で @h-kitagawa さんからコメントを頂いた

> どうするのが一番いいのかはわかりませんが，一つの案としては，
>  * `\shipout` 実行時の組方向が横組なら `\yoko` 実行せずそのまま．
>  * そうでないときは従来どおり `\__shipout_execute_cont:` を横組ボックス `\l__platex_shipout_dummy_box` で括って実行するが，処理終了時に `\box\l__platex_shipout_dummy_box` してメイン垂直リストに中身を戻す
>  * `\l_shipout_box` が横組でない場合は事前に `\setbox\l_shipout_box\vbox{\yoko\box\l_shipout_box}` して横組化する

はまだ検討できていません。

**Comment by h20y6m** [comment]
> [aminophen/platex-tools#16 (comment)](https://github.com/aminophen/platex-tools/pull/16#issuecomment-691794512) で @h-kitagawa さんからコメントを頂いた
> 
> > どうするのが一番いいのかはわかりませんが，一つの案としては，
> > 
> > * `\shipout` 実行時の組方向が横組なら `\yoko` 実行せずそのまま．
> > * そうでないときは従来どおり `\__shipout_execute_cont:` を横組ボックス `\l__platex_shipout_dummy_box` で括って実行するが，処理終了時に `\box\l__platex_shipout_dummy_box` してメイン垂直リストに中身を戻す
> > * `\l_shipout_box` が横組でない場合は事前に `\setbox\l_shipout_box\vbox{\yoko\box\l_shipout_box}` して横組化する
> 
> はまだ検討できていません。

やってみました（h20y6m_candidate_3 ブランチ）。

一応うまく動いている気がします。
（everyshi_small.tex と everyshi_tikz_2.tex でエラーが出ますが別の原因だと思う……）

ただ、

> 処理終了時に `\box\l__platex_shipout_dummy_box` してメイン垂直リストに中身を戻す

の部分がどうすればよいかわからず実装できていません。

**Comment by aminophen** [comment]
@h20y6m 実装ありがとうございます。

> everyshi_small.tex

こちらではエラーが出ませんでしたが，そちらではどんなエラーが出ていますでしょうか？

> everyshi_tikz_2.tex 

こちらでも再現。

```
! Incompatible direction list can't be unboxed.
\pgfutil@insertatbegincurrentpagefrombox ...l@abb 
                                                  \hskip -\pgf@temp \relax #1}
l.19 ...ransparent!0, outer color=transparent!100]
                                                  
?
```

> メイン垂直リストに中身を戻す

これは私もよくわかりません。（`\box_use:N` は \copy を意味するので，代わりに \box を意味する `\box_use_drop:N` を使ってみたけどやはり無限ループするらしい。）

**Comment by aminophen** [comment]
> everyshi_small.tex

もし「filehook の \InputIfFileExists が未対応」というエラーであれば，plautopatch 開発版 aminophen/plautopatch@b069e81 をお使いください。

しかし一応 platex.cfg (candidate 03) を使えば platex-dev で plautopatch を使う必要もなくなるので，テストケース everyshi_small.tex も調整しました。

**Comment by h20y6m** [comment]
> もし「filehook の \InputIfFileExists が未対応」というエラーであれば

おっしゃる通りのエラーです。

plautopatch 開発版もしくは調整された everyshi_small.tex  でエラーはでなくなりました。

**Comment by aminophen** [comment]
> everyshi_tikz_2.tex

こちらは，私の勘違いでなければ

* platex-dev + platex.cfg (candidate 3) においては「pxeveryshi.sty は不要だが，pxpgfrcs.sty はまだ必要である」という状況らしく，ひとまず \usepackage{pxpgfrcs} でエラーが消えます。
* ところが，エラーは消えても正しく色が塗られません。生成した DVI を `dvispc -s` で読んでみると，どうやら TikZ/PGF 側が \special を DVI に吐き出す過程を失敗しているように見えます。

→ この件は pgf-tikz/pgf#900 で既に検討が進んでいるように思います。

**Comment by aminophen** [comment]
> h20y6m_candidate_3 ブランチ

うまく動いていそうで，残るは「メイン垂直リストに中身を戻す」の実現ができるかどうか，といったところでしょうか (atbegshi_nextpage_tate.tex)。platex.cfg のコメントアウトを外すと確かに無限ループしますが，私も原因がよくわかりません。

**Comment by h-kitagawa** [comment]
> メイン垂直リストに中身を戻す

言い出しっぺですが，私もよくわかりません．
```
      \box_set_ht:Nn \l__platex_shipout_dummy_box { 0pt }
      \box_set_dp:Nn \l__platex_shipout_dummy_box { 0pt }
      \box_set_wd:Nn \l__platex_shipout_dummy_box { 0pt }
      \vtop to 0pt{\vskip\textwidth \box_use:N \l__platex_shipout_dummy_box \vss}
```
のようにするなども考えましたが，multicol パッケージが絡むと (pxatbegshi-03-multicol) 依然として無限ループです．

「中身が空リストのボックスか」という判定ができたらいいのですけどね……．

**Comment by aminophen** [comment]
検討ありがとうございました。

> メイン垂直リストに中身を戻す

これを実現する目的は「縦組クラスで aminophen/platex-tools#15 の使用方法をサポート（？）するため」に限られ，横組クラスでは「`\l__platex_shipout_dummy_box` で括る」を実行しないので本家と互換になっていますから，無理に対応しなくても良いのかもしれません。このケースは外すことにしましょうか。

**Comment by h-kitagawa** [comment]
そうですね．aminophen/platex-tools#15 のような例は（私が報告したのですが）「微妙なところを突いた」ものだと感じているので，plnewsc に「pLaTeX ではそのような shipout へのフックはサポートしない」と明示していれば外してしまって良いと思います．

**Comment by aminophen** [comment]
それでは，現状ある platex.cfg (candidate 3) が他のソースでも動くかどうか，もっと多様なソース（本リポジトリにあるもの以外）でも試してみることにします。

また，実装を見るに「LaTeX team にフックを用意してもらえば済む」という程度のものではなくなってしまいましたので，敢えて本家へのリクエストはしないということで良いでしょうか。

**Comment by aminophen** [comment]
8547fce で plcore.dtx に candidate 3 を取り込みました。

`pLaTeX2e <2020-10-01>-pre-2`

としてあります。

**Comment by aminophen** [comment]
`\__shipout_execute_cont:` の説明 (plcore.dtx -> pldoc.pdf)：

``` tex
% \LaTeXe~2020-10-01以降：\file{ltshipout.dtx}がベースです。
% ただし、縦組クラスでも通るようにするため、以下の方法を採ります。
% \begin{itemize}
% \item |\shipout|実行時の組方向が横組なら、|\yoko|を実行せずそのまま。
% \item 横組でない場合は|\__shipout_execute_cont:|を横組ボックス\\
%       |\l__platex_shipout_dummy_box|で括って実行する（※）。
% \item |\l_shipout_box|が横組でない場合は事前に横組化する。
% \end{itemize}
% 注意：上記※の実装により、縦組クラスでは
% 「|\AtBeginShipout|の中身が外部垂直モードで実行されること」を
% 想定した使用（例：platex-tools issue \#15）はサポートされません。
% ^^A 従来の\file{pxatbegshi}パッケージにも同様の制約がありました。
% ^^A 本当は、処理終了時に|\box\l__platex_shipout_dummy_box|して
% ^^A メイン垂直リストに中身を戻したいのですが、
% ^^A なぜか無限ループが起きるため実行していません。
```

plnewsc15.tex:

```
注意：実装上の都合により、縦組クラスでは
「|\AtBeginShipout|の中身が外部垂直モードで実行されること」を
想定した使用は\emph{サポートされません}。
（例：|aminophen/platex-tools#15|）
```

**Comment by aminophen** [comment]
オフトピックですが，latex と latex-dev で組版結果が変わる例を見つけました。atbegshi パッケージ依存の [eso-pic](https://www.ctan.org/pkg/eso-pic) というパッケージを使っています。

* ソース：eso-ex1-p.tex（eso-pic に添付の例示ソースを基に作成）
* latex の結果：「用紙の上下左右の端から15mm」が期待どおり囲まれる。
* latex-dev の結果：「用紙の下端から15mm」の付近に横長の箱が現れるだけ。

[eso-ex1.zip](https://github.com/texjporg/tests-shipout/files/5286687/eso-ex1.zip) として添付します。

% なお，platex と platex-dev でも処理結果は同様の差異が生じます。

% article → tarticle に変えた場合：platex では `\RequirePackage{plautopatch}` が必要です。一方 platex-dev では candidate 3 のコードで OK です。やはり処理結果には差異が生じます。

**Comment by aminophen** [comment]
> eso-pic の例 eso-ex1-p.tex

[Chat](https://chat.stackexchange.com/transcript/message/55660212#55660212) で教えてもらいました。これは ltshipout の変更とは関係なく，picture 環境の `\put` の定義が LaTeX2e 2020-10-01 で改訂されて `\@tempdimc` が新たに使われたことで，eso-ex1-p.tex で勝手に使った `\@tempdimc` と衝突したことが原因でした。これは例示ソースの書き方が悪かったわけなので，eso-pic の著者にお知らせしておきます。

**Comment by aminophen** [comment]
pLaTeX が作業中ですが，先に platex-tools と plautopatch を出しました (2020-09-27)。

----

Slack の方で議論していた「candidate 3 の実装を expl3 の文法に則って書く」については，どなたか expl3 の流儀がわかる方に書いていただけるとありがたいです。pLaTeX カーネルに導入予定のため，お手数ですが 'plexpl3' branch (https://github.com/texjporg/platex/tree/plexpl3) を fork して pull request 頂ければと思います。

* Primitive conditional は定義しない
* 引数フォーマット，命名法 etc.

なお，LuaTeX-ja では

> yoko, tate, tate_nomath, tate_math, dtou, utod という 6 パターンを用意しました（LuaTeX-ja では tate_math は utod と同義，tate = tate_math || tate_nomath）

とのことなので，出来れば pLaTeX もこれと同等にしたいです。

**Comment by wtsnjp** [comment]
> 「candidate 3 の実装を expl3 の文法に則って書く」

私の勘違いでなければ，現時点で既に `\tex_yoko:D` を `\platex_direction_yoko:` に変えるぐらいしかやることなさそうですが，どうでしょう．

**Comment by wtsnjp** [comment]
別件です．急ぐ必要はないですが，pLaTeX カーネルでモジュール名 `platex` をしっかり使っていく方針に決めたのであれば [`l3prefixes.csv`](https://github.com/cgnieder/latex3/blob/master/l3kernel/doc/l3prefixes.csv) に登録しておいた方がいいと思います．我々で追加して [latex3/latex3](https://github.com/latex3/latex3) リポジトリにプルリクを出してもいいのですが，LATEX-L メーリスにリクエストを出せば勝手にやってもらえると思います．

**Comment by aminophen** [comment]
ありがとうございます。

plexpl3.code.tex の方は正しく書けているでしょうか？

**Comment by wtsnjp** [comment]
> plexpl3.code.tex の方は正しく書けているでしょうか？

問題ないと思います．`\__platex_explLoaded:` は expl3 の命名的には `\__platex_expl_loaded:` で十分な気がしますが，正直どっちでもいいようなことです．

**Comment by aminophen** [comment]
@wtsnjp 確認ありがとうございます。

> `\tex_yoko:D` を `\platex_direction_yoko:` に変える

変更しました。

> expl3 の命名的には `\__platex_expl_loaded:` で十分

そのようにしました。

> pLaTeX カーネルでモジュール名 `platex` をしっかり使っていく方針

特に協議したわけではないですが，特に異論もないと思いますのでこの方針で決めましょう。

> `l3prefixes.csv` に登録

わかりました。pLaTeX リリースと同時に，登録依頼するということにしましょう。

texjporg/platex@fb758b3 で plnewsc15.tex にも plexpl3 の新設を記載しました。

**Comment by aminophen** [comment]
今朝 pgf, filehook, eso-pic の新版が TeX Live に入ったので，帰ったら確認します。

**Comment by aminophen** [comment]
* filehook 2020/09/27 v0.8：LaTeX2e 2020-10-01 に対応した模様。（jlreq がエラーなく通る）
* eso-pic 2020/09/27 v2.0i：レジスタ名の衝突回避なので，影響なし。
* pgf 2020-09-28 v3.1.6：everyshi_tikz_2.tex の処理結果を見ると「shadings ライブラリの色塗り」が駄目でした。pdflatex-dev は大丈夫，latex-dev + dvipdfmx は駄目らしいので pgf-tikz/pgf#928 に問い合わせました。

**Comment by aminophen** [comment]
> l3prefixes.csv に登録

この意義をよく知らないのですが，ドキュメントを見ると「登録した人の名前」（今回だと J.T.D.C. とする予定）がわかる→コンタクトを取る時の参考になるとのことですが，合っているでしょうか？

例えば今回は同じ platex というモジュール名を LuaTeX-ja でも使おうとしています（コード共通化のため）。複数のパッケージが同じモジュール名を使うことについては問題ないと考えてよいですか？

（今回の pLaTeX と LuaTeX-ja のケースでは，そもそも動作エンジンが違うので「同時に定義されようとして衝突する」というケースは無いでしょうけれども。）

**Comment by wtsnjp** [comment]
> > l3prefixes.csv に登録
> 
> この意義をよく知らないのですが，ドキュメントを見ると「登録した人の名前」（今回だと J.T.D.C. とする予定）がわかる→コンタクトを取る時の参考になるとのことですが，合っているでしょうか？
> 
> 例えば今回は同じ platex というモジュール名を LuaTeX-ja でも使おうとしています（コード共通化のため）。複数のパッケージが同じモジュール名を使うことについては問題ないと考えてよいですか？

第一義的にはモジュール名は名前空間なので，それが意図せず他のパッケージとコンフリクトするようでは困るということで，何かモジュール名を決めるときにすでに使われていないかどうかすぐに確認できるためでしょう．連絡先がわかるというのもありますが，それはおそらく副次的な効果です．

開発元が同じで，すべて了解の上で共通のモジュール名 `platex` を利用するのは，当然まったく問題ないと思います．

ps. "J.T.D.C." というのはまさか，そういう文字列で登録するという意味じゃないですよね？（この acronym では自明に誰も何のことだかわからないと思うので……）

**Comment by aminophen** [comment]
ありがとうございます。それでは，明日夜に pLaTeX を出すつもりですので，その時にメールで platex を追加要請します。

J.T.D.C. はもちろんそのままの文字列ではないです。

**Comment by aminophen** [comment]
https://github.com/texjporg/platex/issues/94#issuecomment-701441297 及び https://oku.edu.mie-u.ac.jp/tex/mod/forum/discuss.php?d=2944 に書き込みましたが `pLaTeX2e <2020-10-01>` をどうにかリリースに漕ぎ着けることができました。ご協力いただきまして大変ありがとうございました。 @h-kitagawa @wtsnjp @h20y6m

**Comment by aminophen** [comment]
> l3prefixes.csv に登録

https://github.com/latex3/latex3/pull/812
