### ISSUE TITLE
output routine 内で \unvbox される状況 (onlyfloat.tex)

### ISSUE THREAD

**Issue by h-kitagawa** [texjporg/tests-shipout#2]
https://github.com/aminophen/platex-tools/pull/16 に書いた話とも一部重複しますが，こちらで述べておきます．

onlyfloat.tex で `! Use \yoko at top of list.` エラーが出る件ですが，`\yoko` 実行直前のリストの内容を出力させたところ，
```
### tate direction, internal vertical mode entered at line 12 (\output routine)

\write-{}
\write-{}
prevdepth ignored
### tate direction, vertical mode entered at line 0
### recent contributions:
\penalty 10000
prevdepth 0.0
```
となっていました．この 2 つの `\write` は `\@doclearpage` 内で実行される
```
\setbox\@tempboxa\vsplit\@cclv to\z@ \unvbox\@tempboxa
```
由来によるものです．

同様に `\output` 内で「ページの中身が戻される」ケースとしては，`\@specialoutput` 内の
```
       \global \setbox\@holdpg \vbox{%
                      \unvbox\@holdpg
                      \unvbox\@cclv
                      \setbox\@tempboxa \lastbox
                      \unskip
                                     }%
       \@pagedp \dp\@holdpg
       \@pageht \ht\@holdpg
       \unvbox \@holdpg
```
が挙げられるでしょうか．

どうすればよいかは悩み中です．安直なものとしては，
> output routine で入った内部垂直モード内だけ組方向変更基準を緩和する 
> (cf. https://github.com/texjporg/tex-jp-build/pull/22)

が考えられますが，LaTeX に合わせて pTeX エンジンを変えるというのもどうもしっくり来ません．

**Comment by aminophen** [comment]
> onlyfloat.tex で `! Use \yoko at top of list.` エラーが出る件

onlyfloat.tex だけでなく pxatbegshi-03-multicol.tex も同様にエラーが出るようで，こちらは onlyfloat.tex のような「2個の `\write-{}`」に留まらず「本当に意味のある物（文字ノード）」がリストに戻されてきます。この場合も考えると，pTeX エンジン側で「組方向変更基準の緩和」をしても，正常な組版結果になるとは限らないと思います。

----

全ての問題の根底には「`\@outputpage` で \shipout される box が \yoko 指定であること」が関係していて，そのように実装されている理由は恐らく「pTeX エンジン側の要請」ではなく「pLaTeX トンボを常に横向きで出力するため」だと私は推測しています。もしこの推測が正しければ「`\@outputpage` の \yoko を削除し，かつトンボは横向きで出す実装」を考案すれば，全てのエラーが消えたりしないでしょうか？（まだ何も考えていませんが）

**Comment by aminophen** [comment]
> トンボは横向き

あと，ヘッダとフッタ（ノンブル）も横向きですね。

**Comment by aminophen** [comment]
> `\@outputpage` の \yoko を削除

コードを読んでみましたが，多くの命令を再構成する必要が生じるらしく，私には出来ませんでした。この方針は取りやめます。

> ページの中身が戻される

このケースも pTeX の改修なしで #1 の candidate 3 なら通るので，その方向で考えたく。
